# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 6, 21, 8, 23, 41, 833346, tzinfo=utc))),
                ('modified', models.DateTimeField(default=datetime.datetime(2017, 6, 21, 8, 23, 41, 833585, tzinfo=utc))),
                ('title', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
                ('snippet', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
